name: Terraform

on:
  push:
    branches: [dev]
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform.yml"

  pull_request:
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform.yml"

  workflow_dispatch:

jobs:
  fmt:
    name: FMT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: terraform fmt -check
        run: terraform fmt -check -recursive -diff

  discover:
    name: Discover Terraform directories
    needs: fmt
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.discover.outputs.directories }}
    steps:
      - uses: actions/checkout@v4

      - name: Discover Terraform root modules
        id: discover
        shell: bash
        run: |
          set -euo pipefail

          directories=$(find . \
            -type f \
            -name '*.tf' \
            -not -path './.terraform/*' \
            -not -path './.git/*' \
            -printf '%h\n' |
            sort -u |
            sed 's#^\./##' |
            jq -R -s -c '
              split("\n")
              | map(select(length > 0))
              | map(select(
                  . != "vpc/modules/vpc"
                ))
            ')

          echo "Discovered Terraform directories:"
          echo "$directories" | jq .

          echo "directories=$directories" >> "$GITHUB_OUTPUT"

  validate:
    name: validate (${{ matrix.directory }})
    needs: discover

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(needs.discover.outputs.directories) }}

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: terraform init
        run: terraform init -backend=false -input=false

      - name: terraform validate
        run: terraform validate

  plan:
    name: plan (${{ matrix.directory }})
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(needs.discover.outputs.directories) }}

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: terraform init
        run: |
          terraform init -input=false

      - name: terraform plan
        run: terraform plan -input=false
