name: Terraform

on:
  push:
    branches: [dev]
    paths:
      - "backup-bucket/**"
      - ".github/workflows/terraform.yml"

  workflow_dispatch: {}

jobs:
  fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: terraform fmt -check
        run: terraform fmt -check -recursive backup-bucket

  discover:
    name: Discover Terraform projects
    needs:
      - fmt
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.find.outputs.directories }}

    steps:
      - uses: actions/checkout@v4

      - name: Find Terraform project
        id: find
        shell: bash
        run: |
          directories='["backup-bucket"]'

          echo "Terraform projects:"
          echo "$directories" | jq .

          echo "directories=$directories" >> "$GITHUB_OUTPUT"

  validate:
    name: Validate ${{ matrix.directory }}
    needs:
      - discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(needs.discover.outputs.directories) }}

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: terraform init
        run: terraform init -backend=false -input=false

      - name: terraform validate
        run: terraform validate

  plan:
    name: Plan ${{ matrix.directory }}
    needs:
      - validate

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(needs.discover.outputs.directories) }}

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: terraform init
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ matrix.directory }}/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}"

      - name: terraform plan
        run: terraform plan -input=false
